[package]
name    = "zkella-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }
soroban-poseidon = { workspace = true }
zkella-verifier-interface = { path = "../verifier-interface" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
zkella-verifier = { path = "../verifier" }
ark-bn254 = "0.5"
ark-ec = "0.5"
ark-ff = "0.5"
ark-std = "0.6"
