/**
 * Stellar Testnet configuration for the ZKELLA stack. Addresses are the
 * `testnet_final` record in deployments.json; keep the two in sync.
 */
export const TESTNET_CONTRACTS = {
  verifier:     'CC2LQPXH3L5YKRP7YJ6UIC57AOGJXBQN4DEKNRU4Y32ABXJZOENCDAX3',
  governance:   'CDTJLTBEKBXRJJKHVI32A5UMBB4UC6VBMDOF7WR43H2SKCCRAVRJWY5Q',
  token:        'CA5TFEVODC25SSEZII2XHB2XMCKFNXNLXRNFTKWPKMT5PCWYZUMLPRUZ',
  swap:         'CBN7JJEPAEA5NCKOECPPGHETAK4CCCUFOBUJCDZ7K7HPIV7Y6ILOC524',
  compliance:   'CDP5SRSUFDVEYHUCUX53SM4PZVTOIHDZR3Z5C7G4TFFKAQSLX64FOZVJ',
  viewingKeys:  'CDT776JLXU5GWRIY6WXLZGVKZ5V4TG32HAITNPFZVX5UCJSMMFHNMEEE',
} as const

export const TESTNET_SOROBAN_RPC = 'https://soroban-testnet.stellar.org'
