/**
 * Stellar Testnet configuration for the ZKELLA stack. Addresses are the
 * `testnet_final` record in deployments.json; keep the two in sync.
 */
export const TESTNET_CONTRACTS = {
  verifier:     'CBVZCE42NSL34LGUJNRKBJTU2RSDIKGJSK4WV5NUPCNWAUCYKK56GWC2',
  governance:   'CA3QHKWLHLVBXFYUGTBWA5GWOX6KWMITIQ6LIJU6LTEZQUW5777XEYST',
  token:        'CAE63TOLHJDZ3AREF22RA26ASF46TIT4Y5JBTREUWJJQ7EJBOUBHPUIG',
  swap:         'CDXUPIAJSGXITDYY3OMWSOP2CW4JEMZHHHXLRDVX6WPG5IBOJ3TEVZOV',
  compliance:   'CCM4NTFPH3D7IYDHVP7HPXHOPSYZMBLB3GRVEXF4YOJ7NJLAHTSEIKW3',
  viewingKeys:  'CD2TTLHD3EY3QRRALPPDSTPRQDR5G3IKNIIYIQGWQZVW2EKHY67YTUS2',
} as const

export const TESTNET_SOROBAN_RPC = 'https://soroban-testnet.stellar.org'
