// Live Testnet validation for Tranche 1 Deliverable 5: shield x4 -> transfer4 -> unshield,
// each proof generated by the SDK and submitted as its own transaction.
// Env: STELLAR_SECRET, TOKEN_ID, ASSET_ID. Requires `npm run build --workspace=sdk`.
const path = require('path')
const { rpc, nativeToScVal, scValToNative, xdr } = require('@stellar/stellar-sdk')
const sdk = path.join(__dirname, '../sdk/dist')
const { ZKELLAKeys } = require(sdk + '/keys/keys')
const { ZKELLAWallet } = require(sdk + '/wallet/wallet')
const { generateTransfer4Proof } = require(sdk + '/prover/transfer4')
const { encryptNote } = require(sdk + '/notes/encrypt')

const b = (...p) => path.join(__dirname, '..', 'circuits', ...p)
const orig = rpc.Server.prototype.sendTransaction
rpc.Server.prototype.sendTransaction = async function (tx) {
  const r = await orig.call(this, tx)
  console.log('   tx:', `https://stellar.expert/explorer/testnet/tx/${r.hash}`, r.status)
  return r
}

const vec = items => xdr.ScVal.scvVec(items.map(i => nativeToScVal(i, { type: 'bytes' })))

;(async () => {
  const { STELLAR_SECRET, TOKEN_ID, ASSET_ID } = process.env
  const keys = await ZKELLAKeys.generate()
  const wallet = new ZKELLAWallet({
    keys: keys.spendingKey, network: 'testnet',
    sorobanRpc: 'https://soroban-testnet.stellar.org', indexerUrl: 'http://unused',
    tokenAddress: TOKEN_ID, stellarSecret: STELLAR_SECRET,
    shieldCircuit: { wasmPath: b('shield/build/shield_js/shield.wasm'), zkeyPath: b('shield/build/shield.zkey') },
    unshieldCircuit: { wasmPath: b('unshield/build/unshield_js/unshield.wasm'), zkeyPath: b('unshield/build/unshield.zkey') },
  })
  const AMOUNT = 1_000_000n

  for (let i = 0; i < 4; i++) {
    console.log(`shield #${i}`)
    const { note, submit } = await wallet.shield({ asset: ASSET_ID, amount: AMOUNT })
    const { leafIndex } = await submit()
    console.log('   leaf', leafIndex, 'value', note.value)
  }

  console.log('transfer4')
  const anchor = await wallet.getMerkleRoot()
  const inputs = []
  for (const n of wallet.notes.slice(0, 4)) {
    inputs.push({ note: n, merklePath: await wallet.getMerklePathBytes(n.leafIndex) })
  }
  const res = await generateTransfer4Proof(
    { inputs, nk: keys.spendingKey.nullifierKey, fee: 0n,
      outputs: [0, 1, 2, 3].map(() => ({ value: AMOUNT, assetId: ASSET_ID })) },
    { anchor, assetId: ASSET_ID },
    b('transfer_4in4out/build/transfer_js/transfer.wasm'), b('transfer_4in4out/build/transfer.zkey'),
  )
  const encs = []
  for (const n of res.outputNotes) encs.push(await encryptNote(n, keys.spendingKey.transmissionKey))
  const structEntries = Object.entries({
    anchor: nativeToScVal(anchor, { type: 'bytes' }),
    asset_id: nativeToScVal(ASSET_ID, { type: 'address' }),
    fee: nativeToScVal(0n, { type: 'i128' }),
    in_value_commits: vec(res.inValueCommits),
    nullifiers: vec(res.nullifiers),
    out_commitments: vec(res.outputNotes.map(n => n.commitment)),
    out_value_commits: vec(res.outValueCommits),
  }).map(([k, v]) => new xdr.ScMapEntry({ key: xdr.ScVal.scvSymbol(k), val: v }))
  const ret = await wallet.submitContractCall(TOKEN_ID, 'transfer4', [
    vec(res.nullifiers), vec(res.outputNotes.map(n => n.commitment)), vec(encs),
    nativeToScVal(res.proof, { type: 'bytes' }), xdr.ScVal.scvMap(structEntries),
  ])
  const leaves = scValToNative(ret)
  console.log('   new leaves', leaves)
  res.outputNotes.forEach((n, i) => { n.leafIndex = leaves[i] })
  wallet.notes = res.outputNotes.slice()

  console.log('unshield')
  const u = await wallet.unshield({ asset: ASSET_ID, amount: AMOUNT, to: wallet.sourceKeypair.publicKey() })
  await u.submit()
  console.log('supply', await wallet.callView(TOKEN_ID, 'shielded_supply', [nativeToScVal(ASSET_ID, { type: 'address' })]))
  process.exit(0)
})().catch(e => { console.error('FAILED:', e); process.exit(1) })
